# Generated by Django 4.2.11 on 2026-04-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cctvfeed_id_alter_gate_id_alter_parkingslot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_parking_space',
            field=models.ForeignKey(blank=True, help_text='Parking space assigned to security personnel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_personnel', to='api.parkingspace'),
        ),
    ]
