# Generated by Django 4.2.11 on 2026-04-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_assigned_parking_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Vendor address'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for vendors', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id',
            field=models.FileField(blank=True, help_text='Government issued ID (Aadhaar/Voter ID/Driving License)', null=True, upload_to='vendor_documents/gov_id/'),
        ),
        migrations.AddField(
            model_name='user',
            name='land_owner_name',
            field=models.CharField(blank=True, help_text='Land owner name for vendors', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='land_tax_receipt',
            field=models.FileField(blank=True, help_text='Land tax payment receipt', null=True, upload_to='vendor_documents/land_tax/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_document',
            field=models.FileField(blank=True, help_text='Business license document', null=True, upload_to='vendor_documents/license/'),
        ),
    ]
