# Generated by Django 4.2.11 on 2026-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_vehiclelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle registration number', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('suv', 'SUV'), ('pickup', 'Pickup'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback')], help_text='Type of vehicle', max_length=20),
        ),
    ]
