# Generated by Django 6.0.2 on 2026-04-12 09:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reservation_vehicle_number_reservation_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='One-time booking/reservation fee in Rs (default Rs 20)', max_digits=8),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Hourly parking rate in Rs (default Rs 30/hr)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='cctvfeed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(blank=True, max_length=200)),
                ('user_email', models.CharField(blank=True, max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=15)),
                ('slot_id', models.CharField(help_text='Slot identifier at time of payment', max_length=10)),
                ('slot_label', models.CharField(blank=True, max_length=50)),
                ('parking_space_name', models.CharField(max_length=100)),
                ('parking_space_location', models.TextField(blank=True)),
                ('payment_type', models.CharField(choices=[('booking', 'Booking Fee'), ('final', 'Final Fee')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_ref', models.CharField(help_text='Internal transaction reference', max_length=40, unique=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
