# Generated by Django 4.2.11 on 2026-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_cctvfeed_id_alter_gate_id_alter_parkingslot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_booking_payment', 'Pending Booking Payment'), ('reserved', 'Reserved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_booking_payment', max_length=40),
        ),
    ]
