# Generated by Django 4.2.11 on 2026-04-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='estimated_duration_mins',
            field=models.PositiveIntegerField(blank=True, help_text='User estimated parking duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_checkin_time',
            field=models.TimeField(blank=True, help_text='Expected time of arrival', null=True),
        ),
    ]
