# Generated by Django 4.2.11 on 2026-04-26 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_reservation_estimated_duration_mins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='expected_checkin_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='expected_checkin_time',
            field=models.DateTimeField(blank=True, help_text='Expected time of arrival', null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('booking', 'Booking'), ('wallet', 'Wallet'), ('space', 'Space'), ('system', 'System'), ('cancellation', 'Cancellation')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
