# Generated by Django 4.2.11 on 2026-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_reservation_expected_checkin_time_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Reason for cancellation', max_length=255),
        ),
    ]
